### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by RealSamiru** [DarkTrick/htmlfilemerger#4] opened 2022-02-13 14:57 UTC
```
 File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Username\codes\htmlfilemerger\src\webd\htmlmerger\__main__.py", line 2, in <module>
    main.generic_main ()
  File "C:\Users\Username\codes\htmlfilemerger\src\webd\htmlmerger\htmlmerger\main\main.py", line 4, in generic_main
    main()
TypeError: 'module' object is not callable
```

I'm a beginner.  Please help. If you have a tutorial video for this, please give me the link. Thanks

**Comment by DarkTrick** [comment] 2022-02-14 15:08
I can't reproduce your problem, but I tried something. Can you please do the following:

1. Clone the branch with my changes into a new location `git clone --branch bug4 git@github.com:DarkTrick/htmlfilemerger.git`
2. Try and run again.
3. Report the results.

### Technical details (note for me)
I think the problem is that we have too many same-titled `main`s:
- A folder called `main`
- A file called `main.py` (which in python translates to `main`)
- A function `main` within `main.py`

**Comment by DarkTrick** [comment] 2022-02-23 12:17
The problem should be solved with the latest version. I'll close the issue. If you still experience problems, feel free to reopen.

**Closed as completed by DarkTrick** 2022-02-23 12:17 UTC
